# Generated by Django 4.0.6 on 2022-07-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
